[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Niko Böckerman <git.585wj@slmail.me>"]
readme = "README.md"

[project]
name = "adventofcode"
requires-python = ">=3.12"

[tool.poe.tasks]
mypy = "mypy ."
pyright = "pyright"
ruff-check = "ruff check"
ruff-check-format = "ruff format --check"
lint = ["ruff-check", "ruff-check-format", "shellcheck", "pyright", "mypy"]

format = "ruff format"
ruff-fix = "ruff check --fix-only"

test = "pytest"

runall = "adventofcode all"
validate = ["lint", "test", "runall"]

[tool.poe.tasks.shellcheck]
shell = """
if [ ! $(command -v shellcheck) ]; then
    echo "shellcheck is not installed"
    exit 0
fi

shellcheck $(git ls-files | grep '\\..*sh')
"""

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.12.5"
joblib = "^1.4.2"
attrs = "^24.2.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
pytest = "^8.3.3"
ruff = "^0.6.9"
poethepoet = "^0.29.0"
snakeviz = "^2.2.0"
tuna = "^0.5.11"
pyinstrument = "^4.7.3"
pyright = {extras = ["nodejs"], version = "^1.1.383"}
joblib-stubs = "^1.4.2.5.20240918"

[tool.poetry.scripts]
adventofcode = "adventofcode.main:app"

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "strict"

[tool.mypy]
python_version = "3.12"
strict_optional = true
enable_incomplete_feature = ["NewGenericSyntax"]

[tool.ruff.lint]
select = [
    "A",  # prevent using keywords that clobber python builtins
    "B",  # bugbear: security warnings
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "G",  # flake8-logging-format
    "I",  # isort
    "N",  # pep8-naming
    "S",  # bandit
    "Q",  # flake8-quotes
    "W",  # pycodestyle warnings
    "C4",  # flake8-comprehensions
    "EM",  # flake8-errmsg
    "FA",  # flake8-future-annotations
    "PL",  # pylint
    "PT",  # flake8-pytest-style
    "TD",  # flake8-todo
    "UP",  # alert you when better syntax is available in your python version
    "ANN",  # flake8-annotations
    "ARG",  # flake8-unused-arguments
    "COM",  # flake8-commas
    "ERA",  # flake8-eradicate
    "DTZ",  # flake8-datetimez
    "FLY",  # flynt
    "ICN",  # flake8-import-conventions
    "INP",  # flake8-no-pep420
    "ISC",  # flake8-implicit-str-concat
    "LOG",  # flake8-logging
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "PTH",  # flake8-use-pathlib
    "PYI",  # flake8-pyi
    "RET",  # flake8-return
    "RSE",  # flake8-raise
    "RUF",  # the ruff developer's own rules
    "SIM",  # flake8-simplify
    "SLF",  # flake8-self
    "T20",  # flake8-print
    "TCH",  # flake8-type-checking
    "TID",  # flake8-tidy-imports
    "TRY",  # tryceratops
    "YTT",  # flake8-2020
    "FURB",  # refurb
    "PERF",  # perflint
    "SLOT",  # flake8-slots
]
ignore = [
    "ANN101",
    "COM812",
    "ISC001",
    "PLR2004",
    "S101",
    "TD002",
    "TD003"
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = ["INP001"]
"adventofcode/main.py" = ["T201"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
