[project]
name = "adventofcode"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs ==24.2.0",
    "typer ==0.13.1",
    "joblib ==1.4.2",
]

[project.scripts]
adventofcode = "adventofcode.main:app"

[tool.poe.tasks]
mypy = "mypy ."
pyright = "pyright"
ruff-check = "ruff check"
ruff-check-format = "ruff format --check"
lint = ["ruff-check", "ruff-check-format", "pyright", "mypy"]

format = "ruff format"
ruff-fix = "ruff check --fix-only"

test = "pytest"

validate = ["lint", "test", "runall"]

[tool.poe.tasks.runall]
cmd = "adventofcode all"
env = { PYTHONWARNINGS = "always,error" }


[dependency-groups]
dev = [
    "ruff ==0.8.0",
    "pyright[nodejs] ==1.1.389",
    "joblib-stubs ==1.4.2.5.20240918",
    "mypy ==1.13.0",
    "pytest ==8.3.3",
    "snakeviz ==2.2.2",
    "tuna ==0.5.11",
    "pyinstrument ==5.0.0",
    "poethepoet ==0.31.0",
]

[tool.pyright]
typeCheckingMode = "strict"

[tool.mypy]
strict_optional = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "D10",
    "FIX",
    "ISC001",
    "PLR2004",
    "S101",
    "TD002",
    "TD003"
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = ["INP001"]
"adventofcode/main.py" = ["T201"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
