[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Niko Böckerman <git.585wj@slmail.me>"]
readme = "README.md"

[tool.poe.tasks]
_black_check = "black --check ."
_isort_check = "isort --check-only ."
mypy = "mypy ."
ruff = "ruff ."
lint = ["_black_check", "_isort_check", "mypy", "ruff"]

black = "black ."
isort = "isort ."
format = ["black", "isort"]

pytest = "pytest ."
test = ["pytest"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
mypy = "^1.7.1"
pytest = "^7.4.3"
ruff = "^0.1.7"
isort = "^5.12.0"
poethepoet = "^0.24.4"

[tool.poetry.scripts]
adventofcode = "adventofcode.main:main"

[tool.mypy]
python_version = "3.12"
strict_optional = true

[tool.ruff]
select = [
    "A",  # prevent using keywords that clobber python builtins
    "B",  # bugbear: security warnings
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "W",  # pycodestyle warnings
    "C90", # mccabe, complexity
    "ISC",  # implicit string concatenation
    "UP",  # alert you when better syntax is available in your python version
    "RUF",  # the ruff developer's own rules
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
