name: uv project setup
description: Setup python, uv and dependencies for project
runs:
  using: composite
  steps:
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@1edb52594c857e2b5b13128931090f0640537287 # v5
      with:
        python-version: 3.13
    - name: Install project dependencies
      run: uv sync
      shell: bash
