name: uv project setup
description: Setup python, uv and dependencies for project
runs:
  using: composite
  steps:
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5
      with:
        python-version: 3.13
    - name: Install project dependencies
      run: uv sync
      shell: bash
