name: uv project setup
description: Setup python, uv and dependencies for project
runs:
  using: composite
  steps:
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6.3.0
      with:
        python-version: 3.13
    - name: Install project dependencies
      run: uv sync
      shell: bash
