name: uv project setup
description: Setup python, uv and dependencies for project
runs:
  using: composite
  steps:
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5
      with:
        python-version: 3.13
    - name: Install project dependencies
      run: uv sync
      shell: bash
