name: uv project setup
description: Setup python, uv and dependencies for project
runs:
  using: composite
  steps:
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6
      with:
        python-version: 3.13
    - name: Install project dependencies
      run: uv sync
      shell: bash
