name: Check - ruff
on:
  pull_request:
    paths:
      - "**.py"
      - "**/py.typed"
      - ".github/actions/uv-project-setup/**"
      - ".github/workflows/check-ruff.yaml"
      - "pyproject.toml"
      - "uv.lock"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/uv-project-setup
      - name: Check ruff
        run: uv run poe check:ruff
      - name: Check format with ruff
        run: uv run poe check:ruff:format
