name: Check - pyright

on:
  pull_request:
    paths:
      - "**.py"
      - "**/py.typed"
      - ".github/actions/uv-project-setup/**"
      - ".github/actions/yarn-project-setup/**"
      - ".github/workflows/check-pyright.yaml"
      - "package.json"
      - "pyproject.toml"
      - "uv.lock"
      - "yarn.lock"
  workflow_call:
  workflow_dispatch:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/uv-project-setup
      - name: Setup yarn tools
        uses: ./.github/actions/yarn-project-setup
      - name: Check pyright
        run: uv run poe check:pyright
