name: Check - mypy
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/uv-project-setup
      - name: Check mypy
        run: uv run poe check:mypy
