name: Check - pyright
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/uv-project-setup
      - name: Setup yarn tools
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@f204e7207f7303c894a97b3ad437855085808476
      - name: Check pyright
        run: uv run poe check:pyright
