name: Check - Devcontainer
on:
  pull_request:
    paths:
      - "**.py"
      - ".devcontainer/**"
      - ".github/workflows/check-devcontainer.yaml"
      - "adventofcode/**/input-*.txt"
      - "pyproject.toml"
      - "uv.lock"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-devcontainer.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
    with:
      runCmd: uv run poe runall
