name: CI + CD
on:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  prebuild-devcontainer:
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
    permissions:
      contents: read
      packages: write
    with:
      cache-type: intermediate
  ci:
    needs: prebuild-devcontainer
    uses: ./.github/workflows/ci.yaml
  deploy-devcontainer-cache:
    needs: ci
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
    with:
      cache-type: final
