name: CI
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
permissions:
  contents: read

jobs:
  check-mypy:
    uses: ./.github/workflows/check-mypy.yaml
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  check-pyright:
    uses: ./.github/workflows/check-pyright.yaml
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  check-ruff:
    uses: ./.github/workflows/check-ruff.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@cefbbbefc1216ea1d0a822149b313c725c5f820b
  test-pytest:
    uses: ./.github/workflows/test-pytest.yaml
  run-all:
    uses: ./.github/workflows/run-all.yaml

  check:
    needs:
      - check-mypy
      - check-prettier
      - check-pyright
      - check-renovate-config
      - check-ruff
      - check-yarn
      - test-pytest
      - run-all
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
