name: CI
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check-devcontainer:
    uses: ./.github/workflows/check-devcontainer.yaml
  check-mypy:
    uses: ./.github/workflows/check-mypy.yaml
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
  check-pyright:
    uses: ./.github/workflows/check-pyright.yaml
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
  check-ruff:
    uses: ./.github/workflows/check-ruff.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
  test-pytest:
    uses: ./.github/workflows/test-pytest.yaml
  run-all:
    uses: ./.github/workflows/run-all.yaml

  check:
    needs:
      - check-devcontainer
      - check-mypy
      - check-prettier
      - check-pyright
      - check-renovate-config
      - check-ruff
      - check-yarn
      - test-pytest
      - run-all
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
