name: CI
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-mypy:
    uses: ./.github/workflows/check-mypy.yaml
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-pyright:
    uses: ./.github/workflows/check-pyright.yaml
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-ruff:
    uses: ./.github/workflows/check-ruff.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  test-pytest:
    uses: ./.github/workflows/test-pytest.yaml
  run-all:
    uses: ./.github/workflows/run-all.yaml
