name: CI
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
permissions:
  contents: read

jobs:
  mise-cache:
    uses: nikobockerman/github-workflows/.github/workflows/mise-prepare-cache.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
  uv-cache:
    needs: mise-cache
    uses: ./.github/workflows/mise-uv-prepare-cache.yaml
  check-mypy:
    needs: uv-cache
    uses: ./.github/workflows/mise-uv-task.yaml
    with:
      task: check:mypy
  check-prettier:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
    with:
      task: check:prettier
  check-pyright:
    needs: uv-cache
    uses: ./.github/workflows/mise-uv-task.yaml
    with:
      task: check:pyright
  check-renovate-config:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
    with:
      task: check:renovateconfig
  check-ruff:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
    with:
      task: "check:ruff ::: check:ruff::format"
  test-pytest:
    needs: uv-cache
    uses: ./.github/workflows/mise-uv-task.yaml
    with:
      task: check:pytest
  run-all:
    needs: uv-cache
    uses: ./.github/workflows/mise-uv-task.yaml
    with:
      task: runall

  check:
    needs:
      - check-mypy
      - check-prettier
      - check-pyright
      - check-renovate-config
      - check-ruff
      - test-pytest
      - run-all
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
