name: CI
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check-devcontainer:
    uses: ./.github/workflows/check-devcontainer.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
  check-mypy:
    uses: ./.github/workflows/check-mypy.yaml
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
  check-pyright:
    uses: ./.github/workflows/check-pyright.yaml
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
  check-ruff:
    uses: ./.github/workflows/check-ruff.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
  test-pytest:
    uses: ./.github/workflows/test-pytest.yaml
  run-all:
    uses: ./.github/workflows/run-all.yaml
