name: CI

on:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:

jobs:
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@d32b3b6765f463389cf43ee69b0bb1a6a8fe80f6
  check-mypy:
    uses: ./.github/workflows/check-mypy.yaml
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@d32b3b6765f463389cf43ee69b0bb1a6a8fe80f6
  check-pyright:
    uses: ./.github/workflows/check-pyright.yaml
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@d32b3b6765f463389cf43ee69b0bb1a6a8fe80f6
  check-ruff:
    uses: ./.github/workflows/check-ruff.yaml
  check-yarn:
    uses: ./.github/workflows/check-yarn.yaml
  test-pytest:
    uses: ./.github/workflows/test-pytest.yaml
  run-all:
    uses: ./.github/workflows/run-all.yaml
