name: Run verifications

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
        with:
          version: "^0.4.20"
          enable-cache: true
      - run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

      - name: Install python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.12
      - run: python --version

      - name: Setup npm
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 22
          cache: npm

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Install npm dev tools
        run: uv run poe sync:npm

      - name: Run validations
        run: uv run poe all
