name: Run verifications

on:
  check_run:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@2e657c127d5b1635d5a8e3fa40e0ac50a5bf6992 # v3
        with:
          version: "^0.4.20"
          enable-cache: true
      - run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

      - name: Install python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.12
      - run: python --version

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Run validations
        run: uvx --from poethepoet poe validate
