name: Mise + uv - prepare cache
on:
  workflow_call:
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare uv cache
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Prepare
        id: prepare
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: |
          echo "UV_CACHE_DIR=${RUNNER_TEMP}/uv-cache" >> "$GITHUB_OUTPUT"
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup mise
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@d2cedde68b0ee836c0e6fc12c818068a2d502f75 # v1.0.17
      - name: uv cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ${{ steps.prepare.outputs.UV_CACHE_DIR }}
            .venv
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-
      - name: Install uv dependencies
        env:
          UV_CACHE_DIR: ${{ steps.prepare.outputs.UV_CACHE_DIR }}
        run: uv sync --locked
      - name: Minimize uv cache
        env:
          UV_CACHE_DIR: ${{ steps.prepare.outputs.UV_CACHE_DIR }}
        run: uv cache prune
