name: Mise + uv - run task
on:
  workflow_call:
    inputs:
      task:
        description: Task to run
        required: true
        type: string
permissions:
  contents: read

jobs:
  task:
    name: Run mise task with uv - ${{ inputs.task }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Prepare
        id: prepare
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: |
          echo "UV_CACHE_DIR=${RUNNER_TEMP}/uv-cache" >> "$GITHUB_OUTPUT"
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup mise
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@7b957b33a78854e2d90110e7d397e55fbe09abc8 # v1.0.15
      - name: Restore uv cache
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          fail-on-cache-miss: true
          key: uv-${{ hashFiles('uv.lock') }}
          path: |
            ${{ steps.prepare.outputs.UV_CACHE_DIR }}
            .venv
      - name: Install project
        env:
          UV_CACHE_DIR: ${{ steps.prepare.outputs.UV_CACHE_DIR }}
        run: uv sync --locked --offline
      - name: Run task - ${{ inputs.task }}
        env:
          UV_CACHE_DIR: ${{ steps.prepare.outputs.UV_CACHE_DIR }}
        run: mise run ${{ inputs.task }}
