name: Mise + uv - prepare cache
on:
  workflow_call:
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare uv cache
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Prepare
        id: prepare
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: |
          echo "UV_CACHE_DIR=${RUNNER_TEMP}/uv-cache" >> "$GITHUB_OUTPUT"
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup mise
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@846d10210d3aec6fc26b717f13a121fce2d4eb94 # v1.0.9
      - name: uv cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ${{ steps.prepare.outputs.UV_CACHE_DIR }}
            .venv
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-
      - name: Install uv dependencies
        env:
          UV_CACHE_DIR: ${{ steps.prepare.outputs.UV_CACHE_DIR }}
        run: uv sync --locked
      - name: Minimize uv cache
        env:
          UV_CACHE_DIR: ${{ steps.prepare.outputs.UV_CACHE_DIR }}
        run: uv cache prune
