name: Run - all
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup project
        uses: ./.github/actions/uv-project-setup
      - name: Run all
        run: uv run poe runall
