name: Check - pytest

on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
  workflow_call:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/uv-project-setup
      - name: Check pytest
        run: uv run poe check:pytest
